name: Build Docker Image

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - 'Dockerfile'
      - 'west.yml'
      - 'scripts/install_dependencies.sh'
      - 'scripts/setup_python_venv.sh'
      - 'scripts/setup_west_workspace.sh'

jobs:
  build-separately:
    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
            arch: amd64
          - os: ubuntu-24.04-arm
            arch: arm64

    runs-on: ${{ matrix.os }}

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build for ${{ matrix.arch }}
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          platforms: linux/${{ matrix.arch }}
