## This workflow is triggered when files related to building the container have changed.
## If the branch is not main, the container will not be pushed to the registry

name: Build Docker Image

on:
  push:
    paths:
      - 'Dockerfile'
      - 'west.yml'
      - 'scripts/install_dependencies.sh'
      - 'scripts/setup_python_venv.sh'
      - 'scripts/setup_west_workspace.sh'
  workflow_dispatch:

jobs:
  build-separately:
    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
            arch: amd64
          - os: ubuntu-24.04-arm
            arch: arm64

    runs-on: ${{ matrix.os }}

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Add SHORT_SHA env
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

      - name: Build for ${{ matrix.arch }}, push = ${{ github.ref == 'refs/heads/main' }}
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.ref == 'refs/heads/main' }}
          platforms: linux/${{ matrix.arch }}
          provenance: false
          sbom: false
          tags: |
            ghcr.io/${{ github.repository }}:${{ matrix.arch }}-${{ env.SHORT_SHA }}
            ghcr.io/${{ github.repository }}:${{ matrix.arch }}-latest

  consolidate:
    needs: build-separately
    runs-on: ubuntu-24.04
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Add SHORT_SHA env
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

      - name: Create and push multi-arch manifest with SHA tag
        run: |
          docker manifest create ghcr.io/${{ github.repository }}:${{ env.SHORT_SHA }} \
            ghcr.io/${{ github.repository }}:amd64-${{ env.SHORT_SHA }}  \
            ghcr.io/${{ github.repository }}:arm64-${{ env.SHORT_SHA }}

          docker manifest push ghcr.io/${{ github.repository }}:${{ env.SHORT_SHA }}

      - name: Create and push multi-arch manifest with 'latest' tag
        run: |
          docker manifest create ghcr.io/${{ github.repository }}:latest \
            ghcr.io/${{ github.repository }}:amd64-latest  \
            ghcr.io/${{ github.repository }}:arm64-latest

          docker manifest push ghcr.io/${{ github.repository }}:latest
